### ISSUE TITLE
architecture(runtime): adopt Lima as VM lifecycle boundary and retire direct managed-QEMU ownership

### ISSUE THREAD

**Issue by yohnark** [yohn-jp/mottainai#600]
## Task

Redefine Mottainai local Runtime architecture around Lima as the initial local VM lifecycle/provider boundary, with Mottainai owning the declarative Runtime contract and canonical Linux/NixOS Runtime Appliance while Lima owns local VM lifecycle and host/VMM integration.

This Issue records the architecture decision, migration boundaries, and downstream Issue changes before implementation work proceeds.

## Reason

Current Runtime work has expanded Mottainai ownership downward into QEMU distribution and VM plumbing:

- #310 defines a Mottainai-specific managed-QEMU artifact/provenance/materialization contract.
- #311 and PR #599 build/package Linux QEMU artifacts directly.
- #261 expects exact managed-QEMU identity plus direct KVM/QMP/SSH evidence.

That provides strong control, but moves Mottainai toward maintaining a QEMU distribution and VM manager. The product's core concern is instead deterministic, isolated coding-agent execution with declarative lifecycle/reconciliation.

Lima already owns the lower local-VM layer: instance lifecycle, QEMU/VZ driver integration, disk/image handling, SSH/guest-agent transport, networking, mounts, host/guest architecture differences, and host-specific virtualization behavior. Using Lima therefore removes substantial infrastructure code from Mottainai while preserving a strong VM isolation boundary.

### Product boundary

Mottainai owns:

- desired Runtime state and reconciliation policy
- stable Runtime identity
- canonical Linux Runtime Appliance definition
- canonical NixOS Runtime image/closure identity
- Mottainai/Nawabari/Zellij/coding-agent contents of the appliance
- CPU/memory/storage/network/mount policy expressed as Mottainai Runtime specification
- supported Runtime-provider/version contract
- host capability validation required before production start
- guest readiness and Mottainai service readiness
- fail-closed behavior when required virtualization capabilities are unavailable
- evidence connecting Mottainai commit, Runtime spec, appliance/image identity, provider identity, and live Runtime instance

Mottainai does not own:

- QEMU source builds or binary distribution
- QEMU executable/library/firmware packaging schema
- QEMU command-line construction for Lima-managed local Runtime
- QEMU machine/device topology for Lima-managed local Runtime
- disk implementation details below the declared Runtime spec
- virtual NIC implementation details
- SSH implementation/key transport internals supplied by a provider
- host/guest agent transport internals supplied by a provider
- host-specific VMM differences that the provider already abstracts
- direct QMP ownership unless a future requirement cannot be met through the supported provider boundary

### Runtime Appliance vs deployment provider

The canonical Mottainai Runtime must be provider-independent at the guest/appliance boundary.

```text
Canonical Mottainai Runtime Appliance
  ├─ NixOS system
  ├─ Mottainai
  ├─ Nawabari
  ├─ Zellij
  └─ coding-agent/runtime dependencies
             |
       provider adapters
        /           \
     Lima          Proxmox
  local host      server/homelab
     |                |
 QEMU/KVM or VZ    QEMU/KVM
```

Lima is the initial local Runtime provider, not the definition of the Runtime itself. The canonical appliance must not become a Lima-specific guest whose semantics or build depend on Lima provisioning internals.

A future Proxmox provider should be able to instantiate the same canonical appliance through Proxmox/QEMU/KVM without placing Lima inside the Proxmox path. Proxmox support is not required by this Issue, but preserving that deployment boundary is an architecture invariant.

### Initial Runtime stack

Initial supported local stack:

```text
Linux host
  -> pinned/supported Lima
  -> Lima QEMU driver
  -> QEMU/KVM
  -> canonical Mottainai NixOS Runtime Appliance
  -> Mottainai / Nawabari / Zellij / coding agents
```

QEMU remains part of the Linux implementation stack, but becomes a Lima implementation dependency rather than a Mottainai product artifact.

Potential server deployment stack:

```text
Mottainai management/provider adapter
  -> Proxmox API
  -> QEMU/KVM
  -> same canonical Mottainai NixOS Runtime Appliance
```

This future path must not require rebuilding the appliance around Lima-specific semantics.

### Platform scope

- Mottainai guest/runtime semantics remain Linux-only.
- Initial production support target is Linux host + Lima + QEMU/KVM.
- macOS may later use the same Mottainai Runtime contract through Lima + Virtualization.framework.
- Windows support is not required for the first supported Runtime profile and must not force Mottainai to own Windows-specific VM plumbing.
- Proxmox may later be supported as a server deployment provider using the same canonical Runtime Appliance.
- Cross-platform/provider support should be achieved through provider capability rather than host-specific logic spread through Mottainai.

### Dependency ownership

Prefer a pinned/reproducible host toolchain, ideally through Nix, containing the supported Lima/QEMU versions rather than a Mottainai-specific QEMU artifact format.

The trust boundary should move from:

```text
Mottainai verifies exact self-built QEMU executable/archive
```

to:

```text
Mottainai verifies supported provider/toolchain identity + virtualization capabilities + canonical appliance identity + Runtime behavior
```

Ambient, unbounded host state must still not silently determine production support. `mottainai-init`/host preparation should establish and validate one supported provider stack rather than accept arbitrary PATH state.

### Provider integration boundary

Use stable/public provider interfaces only. For Lima, prefer `limactl`/documented configuration and machine-readable inspection output over internal Go packages, sockets, private state files, or driver internals. A future Proxmox provider should similarly use its supported API boundary.

Mottainai should expose a narrow provider adapter approximately equivalent to:

```text
ensure(spec)
start(instance)
stop(instance)
status(instance)
exec(instance, command)
inspect(instance)
```

Exact API naming is not decided by this Issue. Do not prematurely build a generic provider framework for hypothetical providers, but keep canonical Runtime semantics independent from Lima so a concrete second provider such as Proxmox does not require redesigning the appliance.

### Runtime specification

Mottainai remains authoritative for a versioned Runtime specification containing only product-level intent, for example:

- Runtime identity/name
- architecture
- CPU
- memory
- persistent storage policy
- canonical appliance/image/closure identity
- explicitly allowed workspace mounts
- networking policy
- required services/readiness
- provider/profile/version constraints

Do not leak QEMU flags, Lima internals, Proxmox internals, or other provider implementation details into the canonical Mottainai Runtime specification unless they represent a genuine product-level invariant.

### Canonical appliance ownership and image outputs

The canonical Runtime Appliance remains a Mottainai artifact/contract, not a generic Lima template.

It should contain the pinned Runtime environment required by Mottainai, including NixOS configuration and required Mottainai/Nawabari/Zellij/coding-agent dependencies.

The preferred model is one canonical NixOS system/appliance definition with provider-compatible delivery artifacts derived from that same definition where necessary. For QEMU/KVM providers this may include raw/qcow2 or another proven format, but the exact delivery format remains subject to spike validation.

Provider-specific metadata, templates, import descriptors, or wrapping may differ. Product semantics and the canonical NixOS configuration must not fork per provider merely to satisfy Lima or Proxmox.

Lima's role is to instantiate and operate the appliance for local Runtime. A future Proxmox provider's role is to import/instantiate and operate the same appliance for server Runtime.

### Mount and filesystem policy

Do not default to broad host-home sharing merely because Lima supports it.

Workspace sharing must remain explicit and bounded. Only paths required by the active task/session should be exposed to the guest. This must remain compatible with Nawabari worktree/resource ownership and Mottainai governance.

Provider convenience features must not silently broaden the appliance's filesystem authority.

### Reconciliation semantics

Mottainai owns desired-state reconciliation; the active provider owns physical VM operations.

Repeated Runtime ensure must remain idempotent at Mottainai level. Existing compatible instances should be inspected/restarted/reconciled rather than recreated without reason. Provider state differences must be translated into bounded Mottainai Runtime state instead of exposing raw Lima/QEMU/Proxmox internals throughout the product.

### Security/support evidence

Initial Linux support must still prove on a real native Linux/KVM host that:

- required KVM capability exists and is actually used
- canonical appliance boots through the supported Lima stack
- Mottainai Runtime becomes health-ready
- repeated ensure/restart/reconcile behavior is deterministic
- instance and guest identity remain stable where required
- unsupported/missing virtualization fails closed before production execution
- only explicitly allowed host paths are exposed
- evidence records exact Mottainai revision, provider/toolchain version, Runtime spec identity, appliance/image identity, architecture, and relevant capability observations

Direct QMP assertions and exact Mottainai-managed QEMU archive hashes are not product requirements under this architecture unless later evidence shows they are necessary to prove a retained invariant.

### Supersede/retire

- #310 managed-QEMU artifact contract: QEMU-specific executable/archive/library/firmware ownership is superseded. Reuse only generic artifact-trust primitives that still make sense for canonical appliance/provider verification.
- #311 Linux managed-QEMU artifacts: no longer required under Lima provider ownership once the Lima spikes prove the replacement path.
- PR #599: closed; do not revive the direct managed-QEMU build workflow unless the Lima decision fails.
- Corresponding macOS/Windows direct-QEMU artifact work under #260 should be re-evaluated and retired where its only purpose is Mottainai-owned QEMU packaging.

### Preserve but revise

- #261: retain real Linux/KVM E2E evidence, rewritten around the supported Lima provider stack rather than exact Mottainai-managed QEMU/QMP ownership after the Lima spikes pass.
- #259/canonical Runtime image work: preserve. Canonical appliance identity becomes more important, not less.
- #264 lifecycle/security invariants: preserve product-level invariants; move physical VM implementation requirements behind the provider boundary.
- Nix packaging/deployment work: preserve where it defines Mottainai/Nawabari/Zellij guest or host closure. Re-evaluate only QEMU-specific custom packaging.

## `mottainai-init` target responsibility

For the initial local provider, `mottainai-init` or equivalent host bootstrap should converge toward:

1. detect supported host/architecture
2. ensure pinned/supported Lima/provider toolchain is available
3. validate required virtualization capability (KVM for initial Linux profile)
4. resolve/verify canonical Mottainai Runtime Appliance image
5. render bounded Lima instance configuration from Mottainai Runtime spec
6. create/start or reconcile the instance through supported Lima interfaces
7. wait for guest/provider readiness
8. verify Mottainai Runtime identity and service readiness
9. report bounded diagnostics/evidence

It should not build QEMU, invent QEMU device topology, package QEMU shared libraries, or maintain a parallel VM lifecycle engine.

Server providers such as Proxmox may have a different bootstrap/import path while consuming the same canonical appliance and Runtime semantics.

## Required pre-adoption spikes

Before irreversible migration, prove two concrete unknowns on a real Linux/KVM environment:

1. **Lima reconciliation compatibility:** drive create/start/stop/restart/inspect and concurrent/repeated ensure scenarios and determine whether Lima's documented state/inspection surfaces are sufficient to preserve #264's product-level state, locking, identity recovery, idempotency, and fail-closed invariants without private-state polling hacks.
2. **Canonical NixOS appliance boot under Lima:** prove the existing canonical NixOS kernel/initrd/disk design can be consumed by Lima with bounded adaptation. If Lima requires reshaping the canonical guest into a Lima-specific provisioning model, stop and reassess the architecture rather than silently coupling the appliance to Lima.

The second spike should explicitly evaluate whether the resulting canonical appliance can remain a generic QEMU/KVM-capable artifact suitable for a future Proxmox import path.

## Open questions for design review

These are intentionally not fixed yet and should be challenged before implementation:

- Exact Lima version/support policy: exact pin vs supported range.
- Whether Lima and QEMU should be supplied entirely through a Nix host closure or Lima may use another supported installation path.
- Canonical NixOS appliance delivery format accepted cleanly by Lima and reusable by QEMU/KVM providers such as Proxmox.
- Whether Mottainai needs a provider-neutral internal interface immediately or may initially implement only `LimaRuntimeProvider` while keeping canonical semantics provider-independent.
- Required machine-readable `limactl` surfaces for inspection/reconciliation and their stability guarantees.
- Exact mapping from Mottainai Runtime state to Lima instance state.
- Storage persistence/recreation rules.
- Network policy and whether default Lima networking is sufficiently bounded for coding-agent execution.
- Mount transport/profile selected for Linux and its security/performance trade-offs.
- How to verify actual KVM acceleration without coupling Mottainai back to QEMU internals.
- Minimum evidence required to claim a host/architecture supported.
- Whether later macOS support should be Lima+VZ with the same appliance/runtime contract.
- What concrete requirements would justify implementing a Proxmox provider and which API/import surface it should use.
- Whether a future provider such as libkrun/Firecracker is worth supporting; current architecture should not preclude replacement but must not add abstraction for hypothetical providers without concrete need.

## Acceptance criteria

- [ ] Architecture decision is validated against current Runtime implementation and active Runtime/Nix Issues; contradictions are listed explicitly.
- [ ] Stable ownership boundary between Mottainai, Lima, host toolchain, canonical Runtime Appliance, and future deployment providers is documented in code/repository architecture docs.
- [ ] Direct managed-QEMU ownership is removed from the forward Runtime plan if the required Lima spikes pass.
- [ ] #310/#311/#261/#264/#260 child impacts are reviewed and updated/closed/superseded as appropriate rather than left stale after spike evidence exists.
- [ ] A bounded Lima provider contract is defined using documented/public Lima interfaces only.
- [ ] Initial supported profile is explicitly defined as Linux host + Lima + QEMU/KVM + canonical Mottainai Linux Runtime Appliance unless design review/spikes establish a stronger alternative.
- [ ] Host bootstrap/reconciliation design identifies exact inputs, outputs, identities, and fail-closed conditions before implementation.
- [ ] Canonical appliance/image ownership and verification remain explicit and independent from Lima implementation details.
- [ ] Canonical NixOS product semantics do not fork per provider; provider-specific delivery wrappers may differ.
- [ ] Canonical appliance design does not preclude direct QEMU/KVM deployment through a future Proxmox provider.
- [ ] Mount/network exposure remains explicit and bounded; broad implicit host sharing is not introduced.
- [ ] Real Linux/KVM E2E evidence plan is updated to prove retained product invariants without requiring Mottainai-managed QEMU artifacts.
- [ ] Lima reconciliation compatibility and canonical NixOS appliance boot spikes are completed before irreversible migration.
- [ ] Migration is decomposed into implementation-sized child Issues before substantial provider implementation begins.

## Constraints

- Do not implement a second VM manager on top of Lima.
- Do not make Lima part of the canonical Runtime Appliance itself.
- Do not make the canonical appliance dependent on Lima-specific provisioning semantics when a provider-independent QEMU/KVM guest boundary is feasible.
- Do not implement Proxmox support in this architecture Issue; preserve the boundary so it can be added later without rebuilding the appliance.
- Do not depend on undocumented Lima internals where documented CLI/config/inspection surfaces exist.
- Do not broaden initial platform support merely because Lima supports more hosts.
- Do not weaken fail-closed virtualization/security behavior solely to simplify integration.
- Do not make QEMU flags or provider-specific details part of Mottainai's canonical Runtime semantics without a product-level reason.
- Do not delete generic verification/security work from #310/#264 until reusable invariants are identified and migrated.
- Keep migration reversible until the Lima-based Linux/KVM golden path is proven end to end.

## Review focus

Before implementation, challenge this decision specifically on:

1. whether Lima actually removes more Mottainai-owned complexity than it adds as a dependency;
2. whether documented Lima interfaces are sufficient for deterministic reconciliation and evidence;
3. whether canonical NixOS appliance boot/image handling is practical without downstream Lima hacks;
4. whether the same canonical appliance can remain suitable for direct QEMU/KVM deployment such as Proxmox;
5. whether KVM use and fail-closed behavior can be proven without direct QEMU ownership;
6. whether Nix can give an adequate reproducible host/provider closure;
7. which existing Runtime contracts are genuinely product invariants versus artifacts of the previous direct-QEMU design.

**Comment by yohnark** [comment]
## Architecture review

I attempted to validate this against a real environment before commenting, but the sandbox I'm running in has no `/dev/kvm`, no virtualization extensions visible in `/proc/cpuinfo` (nested virt not available), and no Nix/QEMU/Lima installed — so an actual `limactl`-driven boot or a reconciler-state-machine reproduction against a live instance isn't possible here. This is a design review based on reading the current implementation and the closed/open child Issues, not a runtime-validated one.

**Overall: agree with the direction.** Three reasons:

1. **Sunk cost is low.** #310/#259/#264 are closed, but that work is contract/verification scaffolding, not shipped artifacts — every host in `src/local-runtime/artifacts.ts` is still `availability: "not-built"`, and #261 (real KVM E2E) is still open/reopened. What gets discarded is design and test infrastructure, not a working QEMU distribution. This is close to the cheapest point in the project to pivot.
2. **The code this removes is concrete and sizeable.** `src/local-runtime/artifacts.ts` (~710 lines: QEMU source build/verify, per-host archive/manifest management) and `qmp.ts` (~332 lines: direct QMP protocol client) are strong candidates to disappear entirely under Lima ownership. `host.ts`'s accelerator probing can mostly become a pre-flight check ahead of `limactl start`.
3. **PR #599 is already closed** (unmerged), consistent with the Migration impact section.

**Where I'd push back / flag risk (things I could not verify without a live Lima+KVM environment):**

- **Reconciler state mapping (open question in the Issue).** `reconciler.ts` currently owns a fairly granular state machine (absent/creating/booting/reachable/reconciling/ready/incompatible/repairable/recreate-required) plus the lock/concurrent-`ensure` and identity-recovery invariants locked down by #264. Whether Lima's own instance states + `limactl` exit codes/JSON output give enough signal to preserve all of that without polling hacks is the single biggest technical unknown here. Recommend a small spike (even on a real Linux/KVM box, not this sandbox) that drives `limactl` through create/stop/restart/concurrent-`ensure` and checks whether the existing #264 test contracts can be re-expressed against it before committing to the full migration.
- **NixOS guest under Lima.** The current guest is a `kernel + initrd + raw disk` NixOS closure (`nix/runtime-image.nix`), started directly — not the cloud-init/qcow2 flow Lima instances typically expect. Getting Lima to boot that guest cleanly (vs. reshaping the guest to fit Lima's provisioning model, which would be a much bigger change than the Issue implies) is the other open question worth resolving with a spike before wider implementation.
- **Housekeeping gap in this Issue's own acceptance criteria:** "#310/#311/#261/#264/#260 child impacts are reviewed and updated/closed/superseded" isn't done yet — #311 is still open even though PR #599 (its linked PR) was closed, and #261 still describes exact-managed-QEMU/QMP evidence rather than the Lima-based stack this Issue proposes. Worth closing/rewriting those before implementation work starts, per the Issue's own migration-impact section.

**What carries over cleanly regardless of the Lima decision:** the declarative contract in `src/runtime-contract/contract.ts`, the fail-closed accelerator/host-key/QMP-privacy invariants from #264, and the explicit mount/network exposure boundary — these are product-level, not QEMU-plumbing artifacts, and should survive the migration essentially unchanged.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by yohnark** [comment]
#601 is now the bounded implementation child for the canonical Runtime Appliance delivery boundary.

It consumes completed #259/#568, keeps NixOS guest semantics provider-independent, uses GitHub Actions for reproducible image/manifest production, and uses Proxmox only for the initial manual QEMU/KVM boot/integration evidence. It deliberately does not implement Proxmox lifecycle automation, Lima, or claim #261 support evidence.

This should precede the Lima guest-compatibility spike so that Lima is tested against an already-defined canonical Appliance rather than defining the guest around Lima.

**Comment by yohnark** [comment]
Architecture supersession note for #622/#635: the provider boundary in this Issue remains valid, but the full-stack appliance-content wording is superseded. The canonical Runtime Appliance is now a bootstrap-only substrate: NixOS/boot/guest integration, network/OpenSSH/control prerequisites, persistent control-state layout, bootstrap/readiness prerequisites, and the minimal bootstrap component. Full Mottainai, Nawabari, Zellij, coding-agent CLIs, and similar fast-moving packages belong to managed Runtime generations and are installed after deployment. PR #637 adds the durable cross-cutting authority in `docs/runtime-architecture.md`, `docs/runtime-state.md`, and `docs/runtime-lifecycle.md`. Provider semantics remain independent: Lima/Proxmox/etc. instantiate the same canonical guest contract.

**Comment by yohnark** [comment]
Architecture completion audit on main `ff720e499d545521314fd87a6b57fa0071108aa2`:

- required spikes #649 and #655 completed;
- canonical provider-independent bootstrap-only Appliance finalized under #622/#624–#630;
- standalone host bootstrap completed under #654 and durable publication under #660/#665;
- production Lima provider orchestration completed under #661/#664 using public `limactl` surfaces;
- #311/#312/#313 direct managed-QEMU packaging tasks are now closed as superseded/not-planned;
- #264 lifecycle/security invariant work is already completed;
- #261 has been rewritten to the retained real Linux/KVM acceptance contract around published `mottainai-init` + pinned Lima + canonical Appliance OCI digest, with no Mottainai-owned QEMU/QMP requirement;
- #658 is folded into #261.

The older body remains useful as the decision/migration record, but its pre-#622 diagrams describing application packages in the base Appliance are historical and superseded by the completed #622 contract. Closing #600 as completed; remaining concrete defects and final real-host certification are tracked independently.
